server:
  port: 8081

spring:
  application:
    name: analytics-service
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: analytics-service-${random.uuid}
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: "*"

app:
  topic: order-events-topic
